export const CODING_CONSEQUENCE = [
  'missense',
  'synonymous',
  'frameshift',
  'no-start',
  'no-stop',
  'nonsense',
  'intronic',
  'intergenic',
  'non-coding',
  "3'UTR",
  "5'UTR",
  'inframe_3',
  'inframe_6',
  'inframe_12',
  'splice_acceptor_-1',
  'splice_acceptor_-2',
  'splice_acceptor_cds_indel',
  'splice_donor_+1',
  'splice_donor_+2',
  'splice_donor_+3',
  'splice_donor_+4',
  'invalid-transcript',
  'unknown',
] as const;
